import type { Metadata } from "next";
import { Inknut_Antiqua, Nunito } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/provider";
import { Footer } from "./startComponents/footer/Footer";
const antiquda = Inknut_Antiqua({
  subsets: ["latin"],
  weight: "400",
  variable: "--var-Inknut_Antiqua",
});
const nunito = Nunito({ subsets: ["latin"], variable: "--var-nunito" });

export const metadata: Metadata = {
  title: "RoomBi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossOrigin="anonymous"
        />
      </head>
      <body
        style={{
          backgroundColor: "var(--gainsboro)",
          fontFamily: " var(--var-nunito), sans-serif",
        }}
        className={(antiquda.variable, nunito.variable, "ms-5 me-5")}
      >
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
