import type { Metadata } from 'next'
import { Inknut_Antiqua, Nunito } from 'next/font/google'
import './globals.css'
import { Providers } from './redux/provider'

const antiquda = Inknut_Antiqua({
	subsets: ['latin'],
	weight: '400',
	variable: '--var-Inknut_Antiqua',
})
const nunito = Nunito({ subsets: ['latin'], variable: '--var-nunito' })

export const metadata: Metadata = {
	title: 'RoomBi',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={(antiquda.variable, nunito.variable)}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
