import { FilterLngObj } from '../../../type/type'

export const filterData: FilterLngObj[] = [
	{
		id: 1,
		type: 'house',
		label: 'Mansions',
		nameUa: 'Особняки',
		nameEn: 'Mansions',
		src: '/filter/Mansions.svg',
	},
	{
		id: 2,
		type: 'sport',
		label: 'Surfing',
		nameUa: 'Серфінг',
		nameEn: 'Surfing',
		src: '/filter/Surfing.svg',
	},
	{
		id: 3,
		type: 'house',
		label: 'houses',
		nameUa: 'Будинки',
		nameEn: 'Houses',
		src: '/filter/Houses.svg',
	},
	{
		id: 4,
		type: 'house',
		label: 'Domehouses',
		nameUa: 'Купольні будинки',
		nameEn: 'Domehouses',
		src: '/filter/Domehouses.svg',
	},
	{
		id: 5,
		type: 'house',
		label: 'Microhouses',
		nameUa: 'Мікро будинки',
		nameEn: 'Microhouses',
		src: '/filter/Microhouses.svg',
	},
	{
		id: 6,
		type: 'house',
		label: 'Countryhouses',
		nameUa: 'Заміські будинки',
		nameEn: 'Countryhouses',
		src: '/filter/Countryhouses.svg',
	},
	{
		id: 7,
		type: 'location',
		label: 'OnBeach',
		nameUa: 'На пляжі',
		nameEn: 'OnBeach',
		src: '/filter/OnBeach.svg',
	},
	{
		id: 8,
		type: 'house',
		label: 'Campsites',
		nameUa: 'Кемпінги',
		nameEn: 'Campsites',
		src: '/filter/Campsites.svg',
	},
	{
		id: 9,
		type: 'location',
		label: 'OnLake',
		nameUa: 'На озері',
		nameEn: 'On lake',
		src: '/filter/OnLake.svg',
	},
	{
		id: 10,
		type: 'house',
		label: 'housesOnTree',
		nameUa: 'Будиночки на дереві',
		nameEn: 'houses on tree',
		src: '/filter/housesOnTree.svg',
	},
	{
		id: 11,
		type: 'house',
		label: 'AutonomousHous',
		nameUa: 'Автономні будинки',
		nameEn: 'Autonomous hous',
		src: '/filter/AutonomousHous.svg',
	},
	{
		id: 12,
		type: 'house',
		label: 'Farms',
		nameUa: 'Ферми',
		nameEn: 'Farms',
		src: '/filter/Farms.svg',
	},
	{
		id: 13,
		type: 'house',
		label: 'Shacks',
		nameUa: 'Халупи',
		nameEn: 'Shacks',
		src: '/filter/Shacks.svg',
	},
	{
		id: 14,
		type: 'location',
		label: 'Arctic',
		nameUa: 'Арктика',
		nameEn: 'Arctic',
		src: '/filter/Arctic.svg',
	},
	{
		id: 15,
		type: 'location',
		label: 'ThereIsLakeNearby',
		nameUa: 'Поряд є озеро',
		nameEn: 'There is lake nearby',
		src: '/filter/ThereIsLakeNearby.svg',
	},
	{
		id: 16,
		type: 'location',
		label: 'islands',
		nameUa: 'Острови',
		nameEn: 'Islands',
		src: '/filter/islands.svg',
	},
	{
		id: 17,
		type: 'location',
		label: 'Tropics',
		nameUa: 'Тропіки',
		nameEn: 'Tropics',
		src: '/filter/Tropics.svg',
	},
	{
		id: 18,
		type: 'location',
		label: 'NationalParks',
		nameUa: 'Національні парки',
		nameEn: 'National parks',
		src: '/filter/NationalParks.svg',
	},
	{
		id: 19,
		type: 'sport',
		label: 'Vineyards',
		nameUa: 'Виноградники',
		nameEn: 'Vineyards',
		src: '/filter/Vineyards.svg',
	},
	{
		id: 20,
		type: 'house',
		label: 'Rooms',
		nameUa: 'Апартаменти',
		nameEn: 'Rooms',
		src: '/filter/Rooms.svg',
	},
	{
		id: 21,
		type: 'house',
		label: 'houseWheels',
		nameUa: 'Будинок на колесах',
		nameEn: 'house Wheels',
		src: '/filter/houseWheels.svg',
	},
	{
		id: 22,
		type: 'house',
		label: 'Caves',
		nameUa: 'Печери',
		nameEn: 'Caves',
		src: '/filter/Caves.svg',
	},
	{
		id: 23,
		type: 'sport',
		label: 'Golf',
		nameUa: 'Гольф',
		nameEn: 'Golf',
		src: '/filter/Golf.svg',
	},
	{
		id: 24,
		type: 'sport',
		label: 'B&B',
		nameUa: 'B&B',
		nameEn: 'B&B',
		src: '/filter/B&B.svg',
	},
	{
		id: 25,
		type: 'house',
		label: 'Earthenhouses',
		nameUa: 'Земляні будинки',
		nameEn: 'Earthen houses',
		src: '/filter/Earthenhouses.svg',
	},
	{
		id: 26,
		type: 'house',
		label: 'Castles',
		nameUa: 'Замки',
		nameEn: 'Castles',
		src: '/filter/Castles.svg',
	},
	{
		id: 27,
		type: 'house',
		label: 'housesWithHistory',
		nameUa: 'Будинки з історією',
		nameEn: 'Castles',
		src: '/filter/housesWithHistory.svg',
	},
	{
		id: 28,
		type: 'house',
		label: 'Luxe',
		nameUa: 'Luxe',
		nameEn: 'Luxe',
		src: '/filter/Luxe.svg',
	},
	{
		id: 29,
		type: 'house',
		label: 'Hanokah',
		nameUa: 'Ханоки',
		nameEn: 'Hanokah',
		src: '/filter/Hanokah.svg',
	},
	{
		id: 30,
		type: 'location',
		label: 'CityOfDreams',
		nameUa: 'Місто мрії',
		nameEn: 'City Of Dreams',
		src: '/filter/CityOfDreams.svg',
	},
	{
		id: 31,
		type: 'house',
		label: 'Cycladichouses',
		nameUa: 'Кікладські будинки',
		nameEn: 'Cycladic houses',
		src: '/filter/Cycladichouses.svg',
	},
	{
		id: 32,
		type: 'house',
		label: 'Windmills',
		nameUa: 'Вітряні млини',
		nameEn: 'Windmills',
		src: '/filter/Windmills.svg',
	},
	{
		id: 33,
		type: 'house',
		label: 'ShepherdWagons',
		nameUa: 'Вівчарські вози',
		nameEn: 'Shepherd Wagons',
		src: '/filter/ShepherdWagons.svg',
	},
	{
		id: 34,
		type: 'house',
		label: 'Ryokans',
		nameUa: 'Рьокани',
		nameEn: 'Ryokans',
		src: '/filter/Ryokans.svg',
	},
	{
		id: 35,
		type: 'house',
		label: 'Yurts',
		nameUa: 'Юрти',
		nameEn: 'Yurts',
		src: '/filter/Yurts.svg',
	},
	{
		id: 36,
		type: 'house',
		label: 'Minsu',
		nameUa: 'Мінсу',
		nameEn: 'Minsu',
		src: '/filter/Minsu.svg',
	},
	{
		id: 37,
		type: 'location',
		label: 'Desert',
		nameUa: 'Пустеля',
		nameEn: 'Desert',
		src: '/filter/Desert.svg',
	},
	{
		id: 38,
		type: 'house',
		label: 'Barns',
		nameUa: 'Сараї',
		nameEn: 'Barns',
		src: '/filter/Barns.svg',
	},
	{
		id: 39,
		type: 'house',
		label: 'Towers',
		nameUa: 'Вежі',
		nameEn: 'Towers',
		src: '/filter/Towers.svg',
	},
	{
		id: 40,
		type: 'house',
		label: 'Floatinghouses',
		nameUa: 'Плавучі будинки',
		nameEn: 'Floating houses',
		src: '/filter/Floatinghouses.svg',
	},
	{
		id: 41,
		type: 'house',
		label: 'Boats',
		nameUa: 'Човни',
		nameEn: 'Boats',
		src: '/filter/Boats.svg',
	},
	{
		id: 42,
		type: 'house',
		label: 'Riads',
		nameUa: 'Ріади',
		nameEn: 'Riads',
		src: '/filter/Riads.svg',
	},
	{
		id: 43,
		type: 'house',
		label: 'Dammuso',
		nameUa: 'Даммузо',
		nameEn: 'Dammuso',
		src: '/filter/Dammuso.svg',
	},
	{
		id: 44,
		type: 'location',
		label: 'NearTheBeach',
		nameUa: 'Біля пляжу',
		nameEn: 'NearThe Beach',
		src: '/filter/NearTheBeach.svg',
	},
	{
		id: 45,
		type: 'sport',
		label: 'Skiing',
		nameUa: 'Катання на лижах',
		nameEn: 'Skiing',
		src: '/filter/Skiing.svg',
	},
	{
		id: 46,
		type: 'house',
		label: 'Containers',
		nameUa: 'Контейнери',
		nameEn: 'Containers',
		src: '/filter/Containers.svg',
	},
	{
		id: 47,
		type: 'OfferedAmenities',
		label: 'CashRegisterParticular',
		nameUa: 'Касовий апарат',
		nameEn: 'Cash Register Particular',
		src: '/filter/CashRegisterParticular.svg',
	},
	{
		id: 48,
		type: 'OfferedAmenities',
		label: 'LargeKitchens',
		nameUa: 'Великі кухні',
		nameEn: 'Large Kitchens',
		src: '/filter/LargeKitchens.svg',
	},
]
