import type { Metadata } from "next";
import { Inknut_Antiqua, Nunito } from "next/font/google";
import { SessionProviderBi } from "@/app/configs/SessionProviderBi";
import { Providers } from "@/app/redux/provider";
import "./globals.css";
import i18nConfig from "../../../i18nConfig";
import { dir } from "i18next";

const antiquda = Inknut_Antiqua({
  subsets: ["latin"],
  weight: "400",
  variable: "--var-Inknut_Antiqua",
});
const nunito = Nunito({ subsets: ["latin"], variable: "--var-nunito" });

export const metadata: Metadata = {
  title: "RoomBi",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
const fonts = `${antiquda.variable} ${nunito.variable} `;
export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossOrigin="anonymous"
        />
      </head>
      <body
        style={{
          backgroundColor: "var(--gainsboro)",
          fontFamily: " var(--var-nunito), sans-serif",
        }}
        className={fonts}
      >
        <SessionProviderBi>
          <Providers>{children}</Providers>
        </SessionProviderBi>{" "}
      </body>
    </html>
  );
}
