import { CardBiProps } from "../type/type";

export const cardData: CardBiProps[] = [
  {
    id: 1,
    title: "Nooks by AdyBeca",
    name: "Домик целиком, Bălnaca, Румыния",
    date: "25фев - 1мар",
    src: [
      "/test1.webp",
      "/test2.webp",
      "/test3.webp",
      "/test4.webp",
      "/test5.webp",
    ],
    price: 50,
    rating: 0,
    choiceGuests: false,
  },
  {
    id: 2,
    title: "Korcula Diamond",
    name: "Роскошная вилла Korcula Diamond",
    date: "1 - 8мар",
    src: [
      "/test2.webp",
      "/test3.webp",
      "/test5.webp",
      "/test1.webp",
      "/test4.webp",
    ],
    price: 60,
    rating: 5,
    choiceGuests: true,
  },
  {
    id: 3,
    title: "Râșnov",
    name: "Дом на дереве, Râșnov, Румыния",
    date: "25-30янв",
    src: [
      "/test5.webp",
      "/test4.webp",
      "/test3.webp",
      "/test2.webp",
      "/test1.webp",
    ],
    price: 70,
    rating: 3,
    choiceGuests: false,
  },
  {
    id: 4,
    title: "Роскошная квартира",
    name: "Жилье целиком, Львов, Украина",
    date: "26-31янв",
    src: [
      "/test3.webp",
      "/test4.webp",
      "/test5.webp",
      "/test2.webp",
      "/test1.webp",
    ],
    price: 70,
    rating: 5,
    choiceGuests: true,
  },
  {
    id: 5,
    title: "двухуровневая квартира",
    name: "Жилье целиком, Киев, Украина",
    date: "31янв-5фев",
    src: [
      "/test4.webp",
      "/test3.webp",
      "/test4.webp",
      "/test5.webp",
      "/test1.webp",
    ],
    price: 70,
    rating: 5,
    choiceGuests: false,
  },
  {
    id: 6,
    title: "Cătunu' lui Victor",
    name: "Старый деревянный амбар, Cătunu' lui Victor",
    date: "31янв-5фев",
    src: [
      "/test1.webp",
      "/test1.webp",
      "/test3.webp",
      "/test4.webp",
      "/test2.webp",
    ],
    price: 70,
    rating: 4,
    choiceGuests: true,
  },
];
